update security vulnerability for gem ffi
GSA/jobs_api pull request #26
Opened 2018-10-11 17:04 UTC by peggles2

Update Security Vulnerability ffi gem. 1.9.18 to 1.9.25

2018-10-11 17:11 UTC, MothOnMars requested changes
The change looks good. Just add the JIRA story # to the commit: 
`'SRCH-whatever update security vulnerability for gem ffi'

2018-10-11 18:13 UTC, MothOnMars commented
@peggles2 , the JIRA story ID needs to be at the beginning of the commit message:
`'SRCH-whatever update security vulnerability for gem ffi'`

That will allow the commit to be auto-associated w/ the JIRA story.

2018-10-15 22:54 UTC, MothOnMars approved these changes

2018-10-18 13:08 UTC, merged

2018-10-18 13:40 UTC, peggles2 commented
Reopen this pull request. I had to tag master before merging so I reverted it. Now its ready to be merged.